version: "2.0"
services:
  database:
    image: postgres:12
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: E?mQupA7n2WZvnzk
      POSTGRES_DB: ibprojecten
      POSTGRES_USER: ibprojecten

  web:
    build: ./web
    ports:
      - "8080:8000"
    links:
      - database:database
    environment:
      DB_NAME: ibprojecten
      DB_PASSWORD: dockeE?mQupA7n2WZvnzk
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "ibprojecten.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
