# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='subdimension',
            field=models.ManyToManyField(related_name='requirement_subdimension', to='ibprojecten.SubDimension'),
        ),
    ]
